package com.enquiry.student.service.impl;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.enquiry.student.binding.LoginForm;
import com.enquiry.student.binding.RegistrationForm;
import com.enquiry.student.binding.UnLockForm;
import com.enquiry.student.entity.UserEntity;
import com.enquiry.student.repositories.UserRepository;
import com.enquiry.student.service.UserService;
import com.enquiry.student.utility.EmailUtils;
import com.enquiry.student.utility.PwdUtils;

@Service
public class UserServiceImpl implements UserService{
	
	@Autowired
	private EmailUtils emailUtils;
	
	@Autowired
	private UserRepository userRepository;
	
	@Autowired
	private PwdUtils pwdUtils;

	@Override
	public String login(LoginForm form) {
		
		return null;
	}
  
	@Override
	public boolean registration(RegistrationForm form) {
		// TODO: Unique Mail Validation
		
		String email = form.getEmail();
		UserEntity userEntity = this.userRepository.findByEmail(email);
		
		if(userEntity!=null) {
			return false;
		}
		
	    // TODO :Temporary Pwd Should be generated by app adn set into entity filed password in dt table
		
		String pwd = this.pwdUtils.generatePwd(email);
		
		//TODO : Copy the properties from binding class and set it into Entity class and Save the entity in database
		UserEntity entity =new UserEntity();
		BeanUtils.copyProperties(form, entity);
		
		//TODO : Set Account status as LOCKED 
		
		entity.setAccountStatus("LOCKED");
		entity.setPassword(pwd);
		
		this.userRepository.save(entity);
		
		
		// TODO :Send  mail with Temporary pwd with link to unlock account
		
		String emailTo = form.getEmail();
		
		String subject="Unlock The Account With Temp Pwd";
		
		StringBuffer body=new StringBuffer();
		body.append("Temporary Pwd :"+pwd);
		body.append("<br>");
		body.append("<br>");
		body.append("<a href=http://localhost:8080/unlock>Click here to unlcok the account</a>");
		
		this.emailUtils.generateMail(emailTo, subject,body.toString());
		
		return true;
	}

	@Override
	public String unLock(UnLockForm form) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String forgotPwd(String email) {
		// TODO Auto-generated method stub
		return null;
	}

}
